# ---
# title: Michael David
# ---
title_prefix:
tag_title_prefix: 
category_title_prefix: 
theme: jekyll-theme-cayman
# theme: jekyll-theme-midnight

# github:
# is_project_page: false

title: Michael David
description: ‎
#Personal Website
